- hosts: all
  tasks:
  - name: Install MySQL DB including dependencies
    become: yes
    apt:
      pkg:
        - mysql-server
        - python3-mysqldb
        - python3-requests
      state: latest 
    when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
  - name: replace-bind
    become: yes
    replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf 
        regexp: '^bind.*$'
        replace: 'bind-address = *'
        backup: yes
    when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")      
  - name: replace-mysqlx-bind
    become: yes
    replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf 
        regexp: '^mysqlx-bind.*$'
        replace: 'mysqlx-bind-address = *'
        backup: yes
    when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")      
  - name: Restart service httpd, in all cases
    service:
      name: mysql
      state: restarted
    when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
  - name: MySQL DB including dependencies on RHEL based systems
    become: yes
    yum:
      name: epel-release
      state: latest
    when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")
  - name: MySQL DB including dependencies on RHEL based systems
    become: yes
    yum:
      name:
        - mysql-server
        - python3-mysql
        - python3-requests
      state: latest
    when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")
  - name: enable mysqld
    service:
      name: mysqld
      enabled: true
      state: restarted     
    when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "RedHat")    
